def getTestData():
    return [
    (1, "To Kill a Mockingbird", "Harper Lee", "Fiction", True),
    (2, "1984", "George Orwell", "Science Fiction", True),
    (3, "Pride and Prejudice", "Jane Austen", "Romance", False),
    (4, "The Great Gatsby", "F. Scott Fitzgerald", "Classic", True),
    (5, "Harry Potter and the Philosopher's Stone", "J.K. Rowling", "Fantasy", True),
    (6, "The Catcher in the Rye", "J.D. Salinger", "Coming-of-Age", False),
    (8, "The Hobbit", "J.R.R. Tolkien", "Fantasy", True),
    (9, "The Lord of the Rings", "J.R.R. Tolkien", "Fantasy", False),
    (10, "The Da Vinci Code", "Dan Brown", "Mystery", True),
    (11, "To Kill a Mockingbird", "Harper Lee", "Fiction", True),
    (12, "War and Peace", "Leo Tolstoy", "Historical Fiction", True),
    (13, "The Catcher in the Rye", "J.D. Salinger", "Coming-of-Age", True),
    (14, "The Hitchhiker's Guide to the Galaxy", "Douglas Adams", "Science Fiction", False),
    (15, "Moby-Dick", "Herman Melville", "Adventure", True),
    (16, "The Hunger Games", "Suzanne Collins", "Dystopian", False),
    (17, "Brave New World", "Aldous Huxley", "Science Fiction", True),
    (18, "The Picture of Dorian Gray", "Oscar Wilde", "Gothic", False),
    (19, "The Martian", "Andy Weir", "Science Fiction", True),
    (20, "Frankenstein", "Mary Shelley", "Gothic", True),
    (21, "Crime and Punishment", "Fyodor Dostoevsky", "Psychological Thriller", True),
    (22, "Alice's Adventures in Wonderland", "Lewis Carroll", "Fantasy", False),
    (23, "The Odyssey", "Homer", "Epic Poetry", True),
    (24, "Dracula", "Bram Stoker", "Gothic Horror", True),
    (25, "The Road", "Cormac McCarthy", "Post-Apocalyptic", False),
    (26, "The Girl with the Dragon Tattoo", "Stieg Larsson", "Thriller", True),
    (27, "Wuthering Heights", "Emily Brontë", "Gothic Romance", False),
    (28, "The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "Mystery", True),
    (29, "The Count of Monte Cristo", "Alexandre Dumas", "Adventure", True),
    (30, "The Handmaid's Tale", "Margaret Atwood", "Dystopian", True),
    (31, "The Alchemist", "Paulo Coelho", "Philosophical fiction", False),
    (32, "One Hundred Years of Solitude", "Gabriel García Márquez", "Magical Realism", True),
    (33, "Lord of the Flies", "William Golding", "Allegorical novel", True),
    (34, "The Old Man and the Sea", "Ernest Hemingway", "Novella", False),
    (35, "A Tale of Two Cities", "Charles Dickens", "Historical Fiction", True),
    (36, "The Divine Comedy", "Dante Alighieri", "Epic Poetry", True),
    (37, "The Brothers Karamazov", "Fyodor Dostoevsky", "Philosophical novel", True),
    (38, "The Shining", "Stephen King", "Horror", False),
    (39, "Slaughterhouse-Five", "Kurt Vonnegut", "Science Fiction", True),
    (40, "Anne of Green Gables", "Lucy Maud Montgomery", "Children's literature", True)
]